// <auto-generated />
using System;
using F1WebGame.Class;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1WebGame.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230513213159_initial4")]
    partial class initial4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("F1WebGame.Class.Cicruit", b =>
                {
                    b.Property<int>("idCircuit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCircuit"));

                    b.Property<int>("PaysidPays")
                        .HasColumnType("int");

                    b.Property<float>("distanceTour")
                        .HasColumnType("real");

                    b.Property<int>("nbTours")
                        .HasColumnType("int");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("premierGP")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("recordTour")
                        .HasColumnType("time");

                    b.Property<int>("saisonidSaison")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("tempsMoyen")
                        .HasColumnType("time");

                    b.Property<int>("usureEssence")
                        .HasColumnType("int");

                    b.Property<int>("usurePneus")
                        .HasColumnType("int");

                    b.HasKey("idCircuit");

                    b.HasIndex("PaysidPays");

                    b.HasIndex("saisonidSaison");

                    b.ToTable("Circuit");
                });

            modelBuilder.Entity("F1WebGame.Class.Ecurie", b =>
                {
                    b.Property<int>("idEcurie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEcurie"));

                    b.Property<int>("PaysidPays")
                        .HasColumnType("int");

                    b.Property<string>("nomEcurie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEcurie");

                    b.HasIndex("PaysidPays");

                    b.ToTable("Ecuries");
                });

            modelBuilder.Entity("F1WebGame.Class.Pays", b =>
                {
                    b.Property<int>("idPays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPays"));

                    b.Property<string>("libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photoDrapeau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPays");

                    b.ToTable("Pays");
                });

            modelBuilder.Entity("F1WebGame.Class.Pilote", b =>
                {
                    b.Property<int>("idPilote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPilote"));

                    b.Property<int>("PaysidPays")
                        .HasColumnType("int");

                    b.Property<int>("VoitureidVoiture")
                        .HasColumnType("int");

                    b.Property<int>("economieEssence")
                        .HasColumnType("int");

                    b.Property<int>("economiePneus")
                        .HasColumnType("int");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vitessePointe")
                        .HasColumnType("int");

                    b.Property<int>("vitesseVirage")
                        .HasColumnType("int");

                    b.HasKey("idPilote");

                    b.HasIndex("PaysidPays");

                    b.HasIndex("VoitureidVoiture");

                    b.ToTable("Pilote");
                });

            modelBuilder.Entity("F1WebGame.Class.Saison", b =>
                {
                    b.Property<int>("idSaison")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSaison"));

                    b.Property<string>("libelleSaison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSaison");

                    b.ToTable("Saison");
                });

            modelBuilder.Entity("F1WebGame.Class.Voiture", b =>
                {
                    b.Property<int>("idVoiture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVoiture"));

                    b.Property<int>("economieEssence")
                        .HasColumnType("int");

                    b.Property<int>("economiePneus")
                        .HasColumnType("int");

                    b.Property<int>("ecurieidEcurie")
                        .HasColumnType("int");

                    b.Property<int>("maniabilite")
                        .HasColumnType("int");

                    b.Property<string>("nomVoiture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("saisonidSaison")
                        .HasColumnType("int");

                    b.Property<int>("vitessePointe")
                        .HasColumnType("int");

                    b.HasKey("idVoiture");

                    b.HasIndex("ecurieidEcurie");

                    b.HasIndex("saisonidSaison");

                    b.ToTable("Voiture");
                });

            modelBuilder.Entity("F1WebGame.Class.Cicruit", b =>
                {
                    b.HasOne("F1WebGame.Class.Pays", "Pays")
                        .WithMany()
                        .HasForeignKey("PaysidPays")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1WebGame.Class.Saison", "saison")
                        .WithMany()
                        .HasForeignKey("saisonidSaison")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pays");

                    b.Navigation("saison");
                });

            modelBuilder.Entity("F1WebGame.Class.Ecurie", b =>
                {
                    b.HasOne("F1WebGame.Class.Pays", "Pays")
                        .WithMany()
                        .HasForeignKey("PaysidPays")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pays");
                });

            modelBuilder.Entity("F1WebGame.Class.Pilote", b =>
                {
                    b.HasOne("F1WebGame.Class.Pays", "Pays")
                        .WithMany()
                        .HasForeignKey("PaysidPays")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1WebGame.Class.Voiture", "Voiture")
                        .WithMany()
                        .HasForeignKey("VoitureidVoiture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pays");

                    b.Navigation("Voiture");
                });

            modelBuilder.Entity("F1WebGame.Class.Voiture", b =>
                {
                    b.HasOne("F1WebGame.Class.Ecurie", "ecurie")
                        .WithMany()
                        .HasForeignKey("ecurieidEcurie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1WebGame.Class.Saison", "saison")
                        .WithMany()
                        .HasForeignKey("saisonidSaison")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ecurie");

                    b.Navigation("saison");
                });
#pragma warning restore 612, 618
        }
    }
}
